name: Deploy

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Deploy to EC2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
      - name: Deploy to EC2
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_ACCESS_ID: ${{ secrets.AWS_ACCESS_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          EC2_INSTANCE: ${{ secrets.EC2_INSTANCE }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          set -e
          echo "Starting deployment to EC2..."
          ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_INSTANCE '
            sudo systemctl start postgresql || true
            export DATABASE_URL=postgresql://postgres:postgres@localhost:5432/productiondb
            cd /home/ubuntu/myproject
            npx prisma migrate deploy --schema=backend/prisma/schema.prisma
            npm run prisma:generate --prefix backend
            npm run seed --prefix backend
            echo "Production DB ready. Deploying app..."
          '
          echo "Deployment to EC2 completed successfully."